services:
  - type: web
    name: file-tagger-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python api_server.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true
    runtime: python
